### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jsalatas** [Zren/plasma-applet-presentwindows#5]
Is this a free open source project? 

I'm asking because there is no license file, so it isn't considered to be open source software. 

https://help.github.com/articles/licensing-a-repository/

Thanks!

**Comment by Zren** [comment]
GPL2+ [just like everything else in KDE/plasma-*](https://github.com/KDE/plasma-desktop/blob/master/applets/kicker/package/metadata.desktop#L108). Normally I tag it in the `metadata.desktop` file [like in here](https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/metadata.desktop#L11) but I'm a bit lazy with the "boring stuff" and it seems I forgot for this widget. Putting it on GitHub implicitly implies it's open source anyways.

I tend to not add LICENSE files since clutters the project root, and Sublime Text doesn't auto-hide license headers (by default at least) so I avoid those as well.

**Comment by jsalatas** [comment]
Nice! Thanks! 

>  Putting it on GitHub implicitly implies it's open source anyways.
Not according to this :)
https://help.github.com/articles/licensing-a-repository/

Anyway. Issue resolved! :)

**Comment by Zren** [comment]
[The icons](https://github.com/Zren/plasma-applet-presentwindows/tree/master/package/contents/icons) were drawn as SVGs by me ([blog post](https://zren.github.io/2018/04/11/unity-ambiance-integreation-for-the-present-windows-button.html)), but it's possible the **designs** could be licensed by [the Unity project](https://git.launchpad.net/unity/tree/) which is GPL too I think, or Microsoft for their icon. I doubt it'll be an issue in either case though.

**Comment by jsalatas** [comment]
I'm actually interesting in reusing ExecUtil.qml in other kde widgets  :)

**Comment by Zren** [comment]
Ah.

I've got several different versions of ExecUtil myself as it's useful in many applications. I've also modified it to use callbacks instead of needing to use if/else conditionals in the signal handler [like I do in this widget](https://github.com/Zren/plasma-applet-presentwindows/blob/master/package/contents/ui/lib/DesktopEffectToggle.qml#L36).

* https://github.com/Zren/plasma-applet-sysmonitordash/blob/master/package/contents/ui/lib/ExecUtil.qml
* https://github.com/Zren/plasma-applet-sysmonitordash/blob/master/package/contents/ui/ListBlockDevices.qml
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/lib/ExecUtil.qml
* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/calendars/ICalManager.qml
